export const WEATHER_UI = {
	BTN_SEARCH: document.querySelector('.weather__btn--search'),
	// SAVED: document.querySelectorAll('.weather__city'),
	SAVED_BTN: document.querySelector('.weather__now--btn'),
	TABS: document.querySelectorAll('.weather__tabs--btn'),
	SEARCH_INPUT: document.querySelector('.weather__city--input'),
	NOW_TEMP: document.querySelector('.weather__now--temp'),
	CITY_NAME: document.querySelectorAll('h3'),
	NOW_IMG: document.querySelector('.weather__now--img'),
	DETAILS_TEMP: document.querySelector('.details__temp'),
	DETAILS_FEELS: document.querySelector('.details__feels'),
	DETAILS_PRES: document.querySelector('.details__precepitations'),
	DETAILS_SUNRISE: document.querySelector('.details__sunrise'),
	DETAILS_SUNSET: document.querySelector('.details__sunset'),
	SAVED_LIST: document.querySelector('.weather_item4'),
	BTN_DEL: document.querySelectorAll('.weather__city--del'),
	FORM: document.querySelector('form'),
	UL: document.querySelector('ul'),
}